// components/BlogPost.jsx

export const blogPosts = [
  {
    title: "What If Warren Buffett Started Investing Today: A Simulation",
    slug: "warren-buffett-investing-2025-hypothetical",
    path: "/blog/warren-buffett-investing-2025-hypothetical",
    description:
      "A thought experiment exploring how Warren Buffett’s strategies might perform if he started investing in today’s market.",
    tag: "Unconventional Investing",
    date: "July 29, 2025",
    image: "/images/blogs/warren-buffet.jpeg",
    readTime: "5 min read",
  },
  {
    title: "What Billionaires Teach Their Kids About Money",
    slug: "what-billionaires-teach-their-kids-about-money",
    path: "/blog/what-billionaires-teach-their-kids-about-money",
    description:
      "Lessons from ultra-wealthy families on raising financially wise children.",
    tag: "Wealth Mindset",
    date: "July 29, 2025",
    image: "/images/blogs/billionaire-kids.jpeg",
    readTime: "4 min read",
  },
  {
    title: "What Gen Z Investors Are Doing Differently",
    slug: "what-gen-z-investors-are-doing-differently",
    path: "/blog/what-gen-z-investors-are-doing-differently",
    description: "Explore how Gen Z is reshaping investing trends in 2025.",
    tag: "Trends",
    date: "July 28, 2025",
    image: "/images/blogs/genz-investing.jpeg",
    readTime: "4 min read",
  },
  {
    title: "Why Your Investment Strategy Is Failing",
    slug: "why-your-investment-strategy-is-failing",
    path: "/blog/why-your-investment-strategy-is-failing",
    description:
      "Identify the blind spots in your strategy and how to fix them.",
    tag: "Strategy",
    date: "July 28, 2025",
    image: "/images/blogs/failing-strategy.jpeg",
    readTime: "5 min read",
  },
  {
    title: "Psychological Traps New Investors Fall Into",
    slug: "psychological-traps-new-investors-fall",
    path: "/blog/psychological-traps-new-investors-fall",
    description: "Avoid the mental pitfalls that derail many new investors.",
    tag: "Behavioral Finance",
    date: "July 27, 2025",
    image: "/images/blogs/psychological-trap.jpeg",
    readTime: "4 min read",
  },
  {
    title: "How Childhood Stories Shape Your Financial Future",
    slug: "how-childhood-shapes-financial-habits",
    path: "/blog/how-childhood-shapes-financial-habits",
    description:
      "Explore how early memories influence your money beliefs and habits.",
    tag: "Psychology",
    date: "July 27, 2025",
    image: "/images/blogs/childhood-money.jpeg",
    readTime: "4 min read",
  },
  {
    title: "How Digital Assets Are Becoming the New Inheritance",
    slug: "digital-assets-new-inheritance",
    path: "/blog/digital-assets-new-inheritance",
    description:
      "From crypto to domain names, see how inheritance is evolving.",
    tag: "Wealth Transfer",
    date: "July 26, 2025",
    image: "/images/blogs/digital-inheritance.jpeg",
    readTime: "5 min read",
  },
  {
    title: "How I Doubled My Investment Returns by Avoiding These Common Traps",
    slug: "how-i-doubled-investment-returns",
    path: "/blog/how-i-doubled-investment-returns",
    description:
      "A personal investing journey with actionable lessons for all.",
    tag: "Personal Finance",
    date: "July 26, 2025",
    image: "/images/blogs/doubled-investment.jpeg",
    readTime: "6 min read",
  },
  {
    title: "How Much Money Do You Need to Stop Working Forever?",
    slug: "how-much-money-to-retire-early",
    path: "/blog/how-much-money-to-retire-early",
    description: "Calculate your FIRE number and plan your early retirement.",
    tag: "Retirement",
    date: "July 25, 2025",
    image: "/images/blogs/stop-working.jpeg",
    readTime: "5 min read",
  },
  {
    title: "How to Build Wealth with Little to No Money in Your 20s",
    slug: "build-wealth-in-20s-no-money",
    path: "/blog/build-wealth-in-20s-no-money",
    description:
      "Start building a solid financial foundation even on a tight budget.",
    tag: "Young Investors",
    date: "July 24, 2025",
    image: "/images/blogs/no-money.jpeg",
    readTime: "4 min read",
  },
  {
    title: "How to Spot a Financial Scam Before You Invest",
    slug: "how-to-spot-a-financial-scam-before-you-invest-2025",
    path: "/blog/how-to-spot-a-financial-scam-before-you-invest-2025",
    description: "Spot red flags and protect yourself from investment fraud.",
    tag: "Safety",
    date: "July 24, 2025",
    image: "/images/blogs/financial-scam.jpeg",
    readTime: "4 min read",
  },
  {
    title: "How to Use Your Hobbies to Create Multiple Income Streams",
    slug: "how-to-monetize-your-hobbies",
    path: "/blog/how-to-monetize-your-hobbies",
    description: "Turn your skills and passions into real income sources.",
    tag: "Side Hustles",
    date: "July 24, 2025",
    image: "/images/blogs/monetize-hobbies.jpeg",
    readTime: "5 min read",
  },
  {
    title: "If Elon Musk Built a Stock Portfolio Instead of a Rocket Company",
    slug: "if-elon-musk-build-stock-portfolio-instead-of-a-rocket-company",
    path: "/blog/if-elon-musk-build-stock-portfolio-instead-of-a-rocket-company",
    description:
      "A fun hypothetical exploring how Elon might allocate capital.",
    tag: "Unconventional Investing",
    date: "July 24, 2025",
    image: "/images/blogs/elon-musk.jpeg",
    readTime: "4 min read",
  },
  {
    title:
      "If You Can Understand This, You’re Already Smarter Than 90% of Investors",
    slug: "smarter-than-90-percent-investors",
    path: "/blog/smarter-than-90-percent-investors",
    description:
      "A simple yet powerful concept that separates great investors from the rest.",
    tag: "Investor Mindset",
    date: "July 24, 2025",
    image: "/images/blogs/smart-investor.jpeg",
    readTime: "4 min read",
  },
  {
    title: "Retirement Planning for Late Starters",
    slug: "retirement-planning-after-40-crorepati",
    path: "/blog/retirement-planning-after-40-crorepati",
    description:
      "It’s not too late to build wealth and retire comfortably—even if you're starting at 40+.",
    tag: "Retirement",
    date: "July 23, 2025",
    image: "/images/blogs/late-retirement.jpeg",
    readTime: "5 min read",
  },
  {
    title: "The 5 Money Beliefs Holding You Back From Your First Million",
    slug: "money-beliefs-holding-you-back-from-your-first-million",
    path: "/blog/money-beliefs-holding-you-back-from-your-first-million",
    description:
      "Break free from limiting money beliefs and start building real wealth.",
    tag: "Mindset",
    date: "July 23, 2025",
    image: "/images/blogs/money-beliefs.jpeg",
    readTime: "4 min read",
  },
  {
    title: "The Hidden Fees That Could Be Eating Your Investment Returns",
    slug: "hidden-investment-fees-india",
    path: "/blog/hidden-investment-fees-india",
    description: "Uncover the fees that silently reduce your long-term gains.",
    tag: "Costs & Fees",
    date: "July 23, 2025",
    image: "/images/blogs/hidden-fees.jpeg",
    readTime: "4 min read",
  },
  {
    title:
      "The One Investment Strategy Billionaires Don’t Want You to Know About",
    slug: "billionaire-secret-investment-strategy",
    path: "/blog/billionaire-secret-investment-strategy",
    description:
      "Explore a simple yet overlooked strategy used by the ultra-wealthy.",
    tag: "Secrets",
    date: "July 23, 2025",
    image: "/images/blogs/billionaire-strategy.jpeg",
    readTime: "5 min read",
  },
  {
    title: "The Rise of Silent Wealth",
    slug: "the-rise-of-silent-wealth",
    path: "/blog/the-rise-of-silent-wealth",
    description:
      "Meet the quiet millionaires who are building wealth under the radar.",
    tag: "Wealth Building",
    date: "July 22, 2025",
    image: "/images/blogs/silent-wealth.jpeg",
    readTime: "4 min read",
  },
  {
    title:
      "The Untold Secrets Billionaires Won’t Admit About Starting With Nothing",
    slug: "untold-secrets-billionaires-starting-with-nothing",
    path: "/blog/untold-secrets-billionaires-starting-with-nothing",
    description:
      "What no one tells you about the real journey from broke to billionaire.",
    tag: "Inspiration",
    date: "July 22, 2025",
    image: "/images/blogs/starting-from-nothing.jpeg",
    readTime: "5 min read",
  },
  {
    title: "This One Investment Habit Could Make You a Millionaire by 50",
    slug: "investment-habit-millionaire-by-50",
    path: "/blog/investment-habit-millionaire-by-50",
    description: "A small daily habit with massive long-term rewards.",
    tag: "Habits",
    date: "July 22, 2025",
    image: "/images/blogs/millionaire-habit.jpeg",
    readTime: "3 min read",
  },
  {
    title: "What Happens If You Never Sell Your Stocks?",
    slug: "never-sell-stocks-long-term-investing",
    path: "/blog/never-sell-stocks-long-term-investing",
    description:
      "Discover the magic of long-term compounding and true wealth building.",
    tag: "Long-Term",
    date: "July 22, 2025",
    image: "/images/blogs/never-sell.jpg",
    readTime: "4 min read",
  },
  {
    title: "What NFTs Mean for the Future of Ownership and Wealth",
    slug: "nfts-ownership-wealth-future",
    path: "/blog/nfts-ownership-wealth-future",
    description:
      "A look into how NFTs are changing value, identity, and inheritance.",
    tag: "Digital Assets",
    date: "July 22, 2025",
    image: "/images/blogs/nfts-wealth.jpeg",
    readTime: "5 min read",
  },
  {
    title: "What Schools Should Teach About Money — But Don’t",
    slug: "what-schools-should-teach-about-money",
    path: "/blog/what-schools-should-teach-about-money",
    description:
      "The most important money lessons that are missing from school curriculums.",
    tag: "Education",
    date: "July 22, 2025",
    image: "/images/blogs/money-education.jpeg",
    readTime: "3 min read",
  },
  {
    title: "What Smart Investors Do During Market Bubbles",
    slug: "how-smart-investors-handle-market-bubbles",
    path: "/blog/how-smart-investors-handle-market-bubbles",
    description:
      "Learn how to survive and thrive during market bubbles and crashes.",
    tag: "Market Psychology",
    date: "July 21, 2025",
    image: "/images/blogs/market-bubbles.jpeg",
    readTime: "4 min read",
  },
  {
    title: "Why Investing Feels Boring—And That’s a Sign You’re Doing It Right",
    slug: "why-investing-feels-boring",
    path: "/blog/why-investing-feels-boring",
    description: "Why the best investors embrace boredom and ignore the hype.",
    tag: "Mindset",
    date: "July 21, 2025",
    image: "/images/blogs/investing-boring.jpeg",
    readTime: "4 min read",
  },
  {
    title: "Why Most Beginners Lose Money and How You Can Win Instead",
    slug: "why-beginners-lose-money",
    path: "/blog/why-beginners-lose-money",
    description: "Avoid beginner mistakes and start investing with confidence.",
    tag: "Beginner Advice",
    date: "July 21, 2025",
    image: "/images/blogs/beginner-mistakes.jpeg",
    readTime: "4 min read",
  },
  {
    title:
      "Why Side Hustles Are the New Full-Time Income for Young Professionals in 2025",
    slug: "side-hustles-as-full-time-income-2025",
    path: "/blog/side-hustles-as-full-time-income-2025",
    description:
      "How the gig economy is replacing traditional jobs for Gen Z and millennials.",
    tag: "Income Streams",
    date: "July 20, 2025",
    image: "/images/blogs/side-hustle.jpg",
    readTime: "4 min read",
  },
  {
    title: "Would You Rather Spend ₹1 Lakh or Invest It?",
    slug: "should-you-spend-or-invest-1-lakh",
    path: "/blog/should-you-spend-or-invest-1-lakh",
    description:
      "An eye-opening comparison of spending vs investing your money.",
    tag: "Decision Making",
    date: "July 19, 2025",
    image: "/images/blogs/spend-vs-invest.jpg",
    readTime: "3 min read",
  },
  {
    title: "You’re Not Lazy — You Just Haven’t Adopted an Owner Mindset Yet",
    slug: "youre-not-lazy-adopt-owner-mindset",
    path: "/blog/youre-not-lazy-adopt-owner-mindset",
    description:
      "Change your relationship with work and money by thinking like an owner.",
    tag: "Mindset Shift",
    date: "July 19, 2025",
    image: "/images/blogs/owner-mindset.jpg",
    readTime: "4 min read",
  },


  {
    title: "How to Get Monthly Pension from NPS",
    slug: "how-to-achieve-a-monthly-pension-of-50k-with-nps",
    path: "/blog/how-to-achieve-a-monthly-pension-of-50k-with-nps",
    description:
      "Learn how NPS can provide you with a regular monthly income after retirement.",
    tag: "Retirement",
    date: "May 25, 2025",
    image: "/images/blogs/registration2.jpeg",
    readTime: "3 min read",
  },
  {
    title: "SIP vs Lumpsum – Which is Better?",
    slug: "sip-vs-lumpsum",
    path: "/blog/sip-vs-lumpsum",
    description:
      "Compare Systematic Investment Plans and lump sum investments to make the right choice.",
    tag: "Investment",
    date: "May 25, 2025",
    image: "/images/blogs/sip-lump2.jpeg",
    readTime: "3 min read",
  },
  {
    title: "Why Risk is a Part of Investing",
    slug: "why-risk-is-part-of-investing",
    path: "/blog/why-risk-is-part-of-investing",
    description:
      "Understand the relationship between risk and returns in investing.",
    tag: "Finance Basics",
    date: "May 26, 2025",
    image: "/images/blogs/riskvsreward3.png",
    readTime: "4 min read",
  },
  {
    title: "Investing vs Gambling – Know the Difference",
    slug: "investing-vs-gambling-whats-the-real-difference",
    path: "/blog/investing-vs-gambling-whats-the-real-difference",
    description:
      "See why investing and gambling are not the same—even if both involve risk.",
    tag: "Finance Mindset",
    date: "May 26, 2025",
    image: "/images/blogs/investingvsgambling.jpeg",
    readTime: "3 min read",
  },
  {
    title: "How to Beat Inflation with Smart Investing",
    slug: "beating-inflation",
    path: "/blog/beating-inflation",
    description:
      "Learn how to protect your money from inflation by making the right investments.",
    tag: "Wealth Building",
    date: "May 28, 2025",
    image: "/images/blogs/inflation2.jpeg",
    readTime: "3 min read",
  },
  {
    title: "What are Stocks, ETFs, Mutual Funds, and Bonds?",
    slug: "what-are-stocks-etfs-mutual-funds-and-bonds",
    path: "/blog/what-are-stocks-etfs-mutual-funds-and-bonds",
    description:
      "A quick guide to different types of financial instruments for new investors.",
    tag: "Education",
    date: "May 28, 2025",
    image: "/images/blogs/stocketf.jpeg",
    readTime: "4 min read",
  },
  {
    title: "How to Create a Passive Income",
    slug: "how-to-create-passive-income-with-investments",
    path: "/blog/how-to-create-passive-income-with-investments",
    description:
      "Explore various strategies to generate income with minimal ongoing effort.",
    tag: "Passive Income",
    date: "May 29, 2025",
    image: "/images/blogs/tree1.jpeg",
    readTime: "5 min read",
  },
  {
    title: "How Does Compounding Work?",
    slug: "how-does-compounding-work",
    path: "/blog/how-does-compounding-work",
    description:
      "Understand the powerful effect of compounding on your investments.",
    tag: "Compounding",
    date: "May 29, 2025",
    image: "/images/blogs/compounding.jpeg",
    readTime: "5 min read",
  },
  {
    title: "How to Diversify Your Investment Portfolio",
    slug: "how-to-diversify-your-investment-portfolio",
    path: "/blog/how-to-diversify-your-investment-portfolio",
    description:
      "Discover the importance of diversification and how it helps reduce risk.",
    tag: "Portfolio Management",
    date: "May 29, 2025",
    image: "/images/blogs/diversify.jpeg",
    readTime: "4 min read",
  },
  {
    title: "How Do Inflation and Taxes Impact Investments?",
    slug: "how-do-inflation-and-taxes-impact-investments",
    path: "/blog/how-do-inflation-and-taxes-impact-investments",
    description:
      "Learn how inflation and taxes can affect your investment returns and what you can do about it.",
    tag: "Tax & Inflation",
    date: "May 29, 2025",
    image: "/images/blogs/tax-inflation.jpeg",
    readTime: "5 min read",
  },
  {
    title: "How to Invest if You are Self-Employed or a Freelancer",
    slug: "how-to-invest-if-you-are-self-employed-or-a-freelancer",
    path: "/blog/how-to-invest-if-you-are-self-employed-or-a-freelancer",
    description:
      "Investment strategies and tips tailored for freelancers and self-employed professionals.",
    tag: "Self-Employed",
    date: "May 29, 2025",
    image: "/images/blogs/self-employed.jpeg",
    readTime: "4 min read",
  },
  {
    title: "Stocks vs Mutual Funds: Which is Better for Indian Investors?",
    slug: "stocks-vs-mutual-funds",
    path: "/blog/stocks-vs-mutual-funds",
    description:
      "Compare stocks and mutual funds to understand which suits your investment goals better in the Indian market.",
    tag: "Investment",
    date: "June 1, 2025",
    image: "/images/blogs/stock-mutualfund.jpeg",
    readTime: "6 min read",
  },
  {
    title: "What is the Difference Between Saving and Investing?",
    slug: "difference-between-saving-and-investing",
    path: "/blog/difference-between-saving-and-investing",
    description:
      "Learn the key differences between saving and investing and when to choose one over the other.",
    tag: "Finance Basics",
    date: "June 1, 2025",
    image: "/images/blogs/saving-investing.jpeg",
    readTime: "3 min read",
  },
];
