export const links = [
  {
    name: "Saving Calculator",
    submenu: true,
    sublinks: [
      { name: "PPF Calculator", link: "/ppf-calculator" },
      { name: "FD Calculator", link: "/fd-calculator" },
      { name: "NPS Calculator", link: "/nps-calculator" },
      { name: "NSC Calculator", link: "/nsc-calculator" },
      { name: "SSY Calculator", link: "/ssy-calculator" },
      { name: "RD Calculator", link: "/rd-calculator" },
      // { name: "APY Calculator", link: "/apy-calculator" },
      { name: "KVP Calculator", link: "/kvp-calculator" },
    ],
  },
  {
    name: "Investment Calculator",
    submenu: true,
    sublinks: [
      { name: "SIP Calculator", link: "/sip-calculator" },
      { name: "Lump Sum Calculator", link: "/lumpsum-calculator" },
      { name: "Mutual Fund Calculator", link: "/mutual-fund-calculator" },
      { name: "Step Up SIP Calculator", link: "/step-up-sip-calculator" },
      { name: "SWP Calculator", link: "/swp-calculator" },
      { name: "GST Calculator", link: "/gst-calculator" },
      { name: "Inflation Calculator", link: "/inflation-calculator" },
      { name: "Gratuity Calculator", link: "/gratuity-calculator" },
      { name: "ROI Calculator", link: "/roi-calculator" },
      { name: "Dividend Yield Calculator", link: "/dividend-calculator" },
      // { name: "EPF Calculator", link: "/epf-calculator" },
      // { name: "Loan EMI Calculator", link: "/loan-emi-calculator" },
      // { name: "Retirement Planning Calculator", link: "/retirement-planning-calculator" },
      // { name: "Tax Calculator", link: "/tax-calculator" },
      // { name: "Education Loan Calculator", link: "/education-loan-calculator" },
      // { name: "Auto Loan Calculator", link: "/auto-loan-calculator" },
      // { name: "Break-even Analysis Calculator", link: "/break-even-analysis-calculator" },
      // { name: "Investment Goal Calculator", link: "/investment-goal-calculator" },
      // { name: "Gold Investment Calculator", link: "/gold-investment-calculator" },
    ],
  },
  {
    name: "Loan Calculator",
    submenu: true,
    sublinks: [
      { name: "EMI Calculator", link: "/emi-calculator" },
      { name: "Car Loan Calculator", link: "/car-loan-calculator" },
      { name: "Home Loan Calculator", link: "/home-loan-calculator" },
      { name: "Personal Loan Calculator", link: "/personal-loan-calculator" },
      { name: "Education Loan Calculator", link: "/education-loan-calculator" },
    ],
  },
  {
    name: "Interest Calculator",
    submenu: true,
    sublinks: [
      {
        name: "Simple Interest Calculator",
        link: "/simple-interest-calculator",
      },
      {
        name: "Compound Interest Calculator",
        link: "/compound-interest-calculator",
      },
      // { name: "Loan Eligibility Calculator", link: "/loan-eligibility-calculator" },
      // { name: "Currency Converter", link: "/currency-converter" },
      // { name: "Financial Dashboard", link: "/financial-dashboard" },
      // { name: "Goal Setting and Alerts", link: "/goal-setting-alerts" },
      // { name: "Expense Tracker", link: "/expense-tracker" },
    ],
  },
  {
    name: "Blog",
    submenu: false,
    link: "/blog",
  },
  // {
  //   name: "Learning Resources",
  //   submenu: true,
  //   sublinks: [
  //     { name: "Financial Glossary", link: "/financial-glossary" },
  //     { name: "Financial Tips & Articles", link: "/financial-tips-articles" },
  //     { name: "FAQs", link: "/faqs" },
  //   ],
  // },
  // {
  //   name: "Contact",
  //   submenu: false,
  //   link: "/contact",
  // },
  // {
  //   name: "About",
  //   submenu: false,
  //   link: "/about",
  // },
];
